### PR TITLE
chore: upgrade node-sass and all js dependencies

### PR DESCRIPTION
**Pull request by fliiiix**
Otherwise this would not build on a system without python2

but it breaks the upload ui O.o

### CODE REVIEW

**Comment by fliiiix** [comment]
@randombenj lets have a look at this next week

**Comment by randombenj** [comment]
image

**Comment by galaplexus** [comment]
You mention the upload ui broken. This was actually broken by another commit. My PR #142 fixes that

**Comment by fliiiix** [comment]
Good call did not realize that - so i guess we need to fix this first 
I'm not to sure about your fix you just made it run again right? this does not actually fix the problem?

**Comment by fliiiix** [comment]
image

TODO
- [ ] There is a UX/UI problem still open
- [ ] fixing the reverted commit

**Comment by galaplexus** [comment]
My proposed solution to have default on latest is this one: https://github.com/docat-org/docat/pull/142/commits/c8f94d7d23a9a1c7e9c5583ab7d750e83bce052a
Works but maybe it's not the most elegant

**Comment by randombenj** [comment]
@galaplexus The problem is that we don't really assume any tag policy. By adding this redirect we start to assume a `latest` tag which might not be the case for certain docs.

**Comment by galaplexus** [comment]
I would suggest to redirect any calls on latest to the highest version according to the recent sorting: [dc3d5ca](https://github.com/docat-org/docat/pull/142/commits/dc3d5ca2b253db0e80a09ec9163068538d12125d)
This is also a feature that would work for #40 
I guess that would mean that we need to forbid the manual tagging of "latest". Backward compatibility?

**Pull request merged**
