### PR TITLE
feat: Add Helm Chart folder

### PR DESCRIPTION
**Pull request by ruimartinsptl**
Added folder `charts` with a Helm Chart to release docat in Kubernetes.

This first iteration just contain the default helm template ( https://helm.sh/docs/helm/helm_create/ ) with the docker image changed to docat, also contains a statefulset requesting 1 GB of storage, in the next iteration we can improve the chart files

### CODE REVIEW

**Comment by randombenj** [comment]
I do like the idea of having a helm chart deployment as we anyway mainly support the docker workflow. 
I will look at this next week in more detail, one thin I would like to change is remove a lot of the default helm boilerplate as IMO it is mostly not needed and can be simplified, it would also be nice to add a CI job to test the deployment.

**Comment by fliiiix** [comment]
can we have that as an extra repo eg something like docat-helm ?

**Comment by fliiiix** [comment]
closed as non active 

feel free to just reopen if you work on it again

**Comment by ruimartinsptl** [comment]
Hello, I can contribute to that `docat-helm` repository, can you create it please? Thanks :)

**Comment by fliiiix** [comment]
Sorry i completely forgot yesterday, you should now have a invite

**Pull request closed without merging**
