### PR TITLE
Fixing: Sorting of versions #142 

### PR DESCRIPTION
**Pull request by fliiiix**
Git history was messed up and merged accidentally reset on `main`.

//cc @randombenj please review commits before merging
//cc @galaplexus please do a proper rebase next time instead of merging

### CODE REVIEW

**Comment by fliiiix** [comment]
@randombenj & @galaplexus please have a look at the code again if that looks fine then i would merge that
(tests and lint are running)

**Comment by lukasweber** [comment]
Currently, versions like `1.0`, `2.0`, etc. also wouldn't work since the versions are parsed really strict by default.

Furthermore, I think the logic can be improved a bit to make it more reliable and maintainable:
```javascript
compareVersions = function(versionNameA, versionNameB) {
    if (versionNameA == "latest") return 1;
    else if (versionNameB == "latest") return -1;
    else  {
        const versionA = semver.coerce(versionNameA) ?? semver.coerce(0);
        const versionB = semver.coerce(versionNameB) ?? semver.coerce(0);
        return semver.compare(versionA, versionB)
    }
}
```
This approach would also prioritize `latest` in every case, but it makes use of `semver.coerce` and falls back to version `0`if a value can't be parsed.

**Comment by lukasweber** [comment]
@fliiiix Yes, that's right. Was just a quick experiment, sorry! :) I actually like the idea of having a fallback to alphabetical sorting.

Without testing it extensively, I think something like that could do the trick. So, every time one of the version can't be parsed it would fall back to a alphabetical sorting using `localeCompare()`. (the previous approach with `versionNameA > versionNameB` didn't compare case insensitive)

```javascript
compareVersions = function(versionNameA, versionNameB) {
  if (versionNameA == "latest") return 1;
      else if (versionNameB == "latest") return -1;
      else  {
          const versionA = semver.coerce(versionNameA);
          const versionB = semver.coerce(versionNameB);
          if (!versionA || !versionB) 
              return versionNameA.localeCompare(versionNameB);
          return semver.compare(versionA, versionB);
      }
   }
}
```

Only the following cases still wouldn't be considered with that approach:
```javascript
    expect(ProjectRepository.compareVersions('0.0.0', '0.0.0.0')).toBeGreaterThan(0);
    expect(ProjectRepository.compareVersions('0.0.0.0', '0.0.0')).toBeLessThan(0);
```

But since these are valid semantic versions, I would personally stick with the handling of the `semver` library.

**Comment by randombenj** [comment]
@lukasweber love it!
The not working cases seem a bit odd to me as changing the versioning scheme will have greater impacts than in the docs anyway 😅

**Comment by fliiiix** [comment]
Thanks @lukasweber 

I replaces the 2 failing edge cases with:
```
expect(ProjectRepository.compareVersions('1.2.0', '1.0')).toBeGreaterThan(0);
expect(ProjectRepository.compareVersions('1.2', '2.0.0')).toBeLessThan(0);
```

Which i feel are more important and implemented (meaning copy pasted your solution) into this commit.

@randombenj @galaplexus @randombenj last chance to review otherwise i will merge this on the weekend

**Comment by fliiiix** [comment]
Thanks everyone involved for this PR @galaplexus, @lukasweber, @randombenj :tada:

**Pull request merged**
